"""
Skill taxonomy for SkillScope — 250+ skills across 10 categories.
"""
from __future__ import annotations

_TAXONOMY: list[dict] = [
    # ── Programming ──────────────────────────────────────────────────────────
    {"skill_name": "Python",        "skill_category": "Programming", "aliases": ["python", "py"]},
    {"skill_name": "Java",          "skill_category": "Programming", "aliases": ["java"]},
    {"skill_name": "C++",           "skill_category": "Programming", "aliases": ["cpp", "c plus plus"]},
    {"skill_name": "C#",            "skill_category": "Programming", "aliases": ["csharp", "c sharp"]},
    {"skill_name": "JavaScript",    "skill_category": "Programming", "aliases": ["JS", "javascript"]},
    {"skill_name": "TypeScript",    "skill_category": "Programming", "aliases": ["TS", "typescript"]},
    {"skill_name": "Go",            "skill_category": "Programming", "aliases": ["golang"]},
    {"skill_name": "Rust",          "skill_category": "Programming", "aliases": ["rust lang"]},
    {"skill_name": "R",             "skill_category": "Programming", "aliases": ["r language", "r programming"]},
    {"skill_name": "Scala",         "skill_category": "Programming", "aliases": ["scala lang"]},
    {"skill_name": "Swift",         "skill_category": "Programming", "aliases": ["swift"]},
    {"skill_name": "Kotlin",        "skill_category": "Programming", "aliases": ["kotlin"]},
    {"skill_name": "PHP",           "skill_category": "Programming", "aliases": ["php"]},
    {"skill_name": "Ruby",          "skill_category": "Programming", "aliases": ["ruby lang"]},
    {"skill_name": "Dart",          "skill_category": "Programming", "aliases": ["dart lang"]},
    {"skill_name": "Lua",           "skill_category": "Programming", "aliases": ["lua"]},
    {"skill_name": "Solidity",      "skill_category": "Programming", "aliases": ["solidity"]},
    {"skill_name": "CUDA",          "skill_category": "Programming", "aliases": ["cuda programming"]},
    {"skill_name": "C",             "skill_category": "Programming", "aliases": ["c language", "c programming"]},
    {"skill_name": "Perl",          "skill_category": "Programming", "aliases": ["perl"]},
    {"skill_name": "Haskell",       "skill_category": "Programming", "aliases": ["haskell"]},
    {"skill_name": "Elixir",        "skill_category": "Programming", "aliases": ["elixir"]},
    {"skill_name": "Clojure",       "skill_category": "Programming", "aliases": ["clojure"]},
    {"skill_name": "Julia",         "skill_category": "Programming", "aliases": ["julia lang"]},
    {"skill_name": "MATLAB",        "skill_category": "Programming", "aliases": ["matlab"]},
    {"skill_name": "Assembly",      "skill_category": "Programming", "aliases": ["asm", "assembly language"]},
    {"skill_name": "Bash",          "skill_category": "Programming", "aliases": ["bash scripting", "shell scripting", "shell script"]},
    {"skill_name": "PowerShell",    "skill_category": "Programming", "aliases": ["powershell scripting"]},
    {"skill_name": "Groovy",        "skill_category": "Programming", "aliases": ["groovy"]},
    {"skill_name": "F#",            "skill_category": "Programming", "aliases": ["fsharp", "f sharp"]},

    # ── Web ──────────────────────────────────────────────────────────────────
    {"skill_name": "React",         "skill_category": "Web", "aliases": ["reactjs", "react.js"]},
    {"skill_name": "Angular",       "skill_category": "Web", "aliases": ["angularjs"]},
    {"skill_name": "Vue",           "skill_category": "Web", "aliases": ["vuejs", "vue.js"]},
    {"skill_name": "Next.js",       "skill_category": "Web", "aliases": ["nextjs"]},
    {"skill_name": "Node.js",       "skill_category": "Web", "aliases": ["nodejs", "node"]},
    {"skill_name": "Django",        "skill_category": "Web", "aliases": ["django"]},
    {"skill_name": "Flask",         "skill_category": "Web", "aliases": ["flask"]},
    {"skill_name": "FastAPI",       "skill_category": "Web", "aliases": ["fastapi"]},
    {"skill_name": "Spring Boot",   "skill_category": "Web", "aliases": ["spring", "springboot"]},
    {"skill_name": "HTML",          "skill_category": "Web", "aliases": ["html5"]},
    {"skill_name": "CSS",           "skill_category": "Web", "aliases": ["css3"]},
    {"skill_name": "Tailwind CSS",  "skill_category": "Web", "aliases": ["tailwind", "tailwindcss"]},
    {"skill_name": "WebAssembly",   "skill_category": "Web", "aliases": ["wasm"]},
    {"skill_name": "tRPC",          "skill_category": "Web", "aliases": ["trpc"]},
    {"skill_name": "Remix",         "skill_category": "Web", "aliases": ["remix.run"]},
    {"skill_name": "Svelte",        "skill_category": "Web", "aliases": ["sveltejs", "svelte.js"]},
    {"skill_name": "Nuxt.js",       "skill_category": "Web", "aliases": ["nuxtjs", "nuxt"]},
    {"skill_name": "Express.js",    "skill_category": "Web", "aliases": ["expressjs", "express"]},
    {"skill_name": "NestJS",        "skill_category": "Web", "aliases": ["nestjs"]},
    {"skill_name": "Laravel",       "skill_category": "Web", "aliases": ["laravel"]},
    {"skill_name": "Ruby on Rails", "skill_category": "Web", "aliases": ["rails", "ror"]},
    {"skill_name": "Gatsby",        "skill_category": "Web", "aliases": ["gatsbyjs"]},
    {"skill_name": "Astro",         "skill_category": "Web", "aliases": ["astro framework"]},
    {"skill_name": "Vite",          "skill_category": "Web", "aliases": ["vitejs"]},
    {"skill_name": "Webpack",       "skill_category": "Web", "aliases": ["webpack"]},

    # ── Data & ML ─────────────────────────────────────────────────────────────
    {"skill_name": "SQL",               "skill_category": "Data & ML", "aliases": ["mysql query", "sql query"]},
    {"skill_name": "Pandas",            "skill_category": "Data & ML", "aliases": ["pandas"]},
    {"skill_name": "NumPy",             "skill_category": "Data & ML", "aliases": ["numpy"]},
    {"skill_name": "Scikit-learn",      "skill_category": "Data & ML", "aliases": ["sklearn", "scikit learn"]},
    {"skill_name": "TensorFlow",        "skill_category": "Data & ML", "aliases": ["tensorflow", "tf"]},
    {"skill_name": "PyTorch",           "skill_category": "Data & ML", "aliases": ["pytorch", "torch"]},
    {"skill_name": "Keras",             "skill_category": "Data & ML", "aliases": ["keras"]},
    {"skill_name": "Spark",             "skill_category": "Data & ML", "aliases": ["apache spark", "pyspark"]},
    {"skill_name": "Hadoop",            "skill_category": "Data & ML", "aliases": ["hadoop"]},
    {"skill_name": "Tableau",           "skill_category": "Data & ML", "aliases": ["tableau"]},
    {"skill_name": "Power BI",          "skill_category": "Data & ML", "aliases": ["powerbi", "power bi"]},
    {"skill_name": "Excel",             "skill_category": "Data & ML", "aliases": ["microsoft excel", "ms excel"]},
    {"skill_name": "dbt",               "skill_category": "Data & ML", "aliases": ["dbt core", "data build tool"]},
    {"skill_name": "Airflow",           "skill_category": "Data & ML", "aliases": ["apache airflow"]},
    {"skill_name": "MLflow",            "skill_category": "Data & ML", "aliases": ["mlflow"]},
    {"skill_name": "Hugging Face",      "skill_category": "Data & ML", "aliases": ["huggingface"]},
    {"skill_name": "LangChain",         "skill_category": "Data & ML", "aliases": ["langchain"]},
    {"skill_name": "LlamaIndex",        "skill_category": "Data & ML", "aliases": ["llama index", "llamaindex"]},
    {"skill_name": "RAG",               "skill_category": "Data & ML", "aliases": ["retrieval augmented generation"]},
    {"skill_name": "Vector Databases",  "skill_category": "Data & ML", "aliases": ["vector db", "vector store"]},
    {"skill_name": "Feature Engineering","skill_category": "Data & ML", "aliases": ["feature engineering"]},
    {"skill_name": "Model Evaluation",  "skill_category": "Data & ML", "aliases": ["model evaluation", "model metrics"]},
    {"skill_name": "Matplotlib",        "skill_category": "Data & ML", "aliases": ["matplotlib"]},
    {"skill_name": "Seaborn",           "skill_category": "Data & ML", "aliases": ["seaborn"]},
    {"skill_name": "Plotly",            "skill_category": "Data & ML", "aliases": ["plotly"]},
    {"skill_name": "SciPy",             "skill_category": "Data & ML", "aliases": ["scipy"]},
    {"skill_name": "XGBoost",           "skill_category": "Data & ML", "aliases": ["xgboost"]},
    {"skill_name": "LightGBM",          "skill_category": "Data & ML", "aliases": ["lightgbm"]},
    {"skill_name": "Kafka",             "skill_category": "Data & ML", "aliases": ["apache kafka"]},
    {"skill_name": "Looker",            "skill_category": "Data & ML", "aliases": ["looker studio", "google looker"]},

    # ── AI & GenAI ────────────────────────────────────────────────────────────
    {"skill_name": "Prompt Engineering",    "skill_category": "AI & GenAI", "aliases": ["prompt engineering"]},
    {"skill_name": "LLM Fine-tuning",       "skill_category": "AI & GenAI", "aliases": ["llm finetuning", "fine tuning llm"]},
    {"skill_name": "ChatGPT API",           "skill_category": "AI & GenAI", "aliases": ["chatgpt", "chat gpt api"]},
    {"skill_name": "OpenAI API",            "skill_category": "AI & GenAI", "aliases": ["openai"]},
    {"skill_name": "Gemini API",            "skill_category": "AI & GenAI", "aliases": ["gemini", "google gemini"]},
    {"skill_name": "Claude API",            "skill_category": "AI & GenAI", "aliases": ["claude", "anthropic claude"]},
    {"skill_name": "Stable Diffusion",      "skill_category": "AI & GenAI", "aliases": ["stable diffusion"]},
    {"skill_name": "Midjourney Prompting",  "skill_category": "AI & GenAI", "aliases": ["midjourney"]},
    {"skill_name": "AI Agents",             "skill_category": "AI & GenAI", "aliases": ["ai agent", "autonomous agents"]},
    {"skill_name": "AutoGen",               "skill_category": "AI & GenAI", "aliases": ["autogen"]},
    {"skill_name": "CrewAI",                "skill_category": "AI & GenAI", "aliases": ["crewai"]},
    {"skill_name": "Embeddings",            "skill_category": "AI & GenAI", "aliases": ["word embeddings", "text embeddings"]},
    {"skill_name": "Semantic Search",       "skill_category": "AI & GenAI", "aliases": ["semantic search"]},
    {"skill_name": "Computer Vision",       "skill_category": "AI & GenAI", "aliases": ["cv", "image recognition"]},
    {"skill_name": "NLP",                   "skill_category": "AI & GenAI", "aliases": ["natural language processing"]},
    {"skill_name": "Speech Recognition",    "skill_category": "AI & GenAI", "aliases": ["speech to text", "asr"]},
    {"skill_name": "Reinforcement Learning","skill_category": "AI & GenAI", "aliases": ["rl", "reinforcement learning"]},
    {"skill_name": "Generative AI",         "skill_category": "AI & GenAI", "aliases": ["genai", "gen ai"]},
    {"skill_name": "Diffusion Models",      "skill_category": "AI & GenAI", "aliases": ["diffusion model"]},
    {"skill_name": "Transformer Models",    "skill_category": "AI & GenAI", "aliases": ["transformers", "attention mechanism"]},

    # ── Cloud & DevOps ────────────────────────────────────────────────────────
    {"skill_name": "AWS",                   "skill_category": "Cloud & DevOps", "aliases": ["amazon web services", "amazon aws"]},
    {"skill_name": "Azure",                 "skill_category": "Cloud & DevOps", "aliases": ["microsoft azure"]},
    {"skill_name": "GCP",                   "skill_category": "Cloud & DevOps", "aliases": ["google cloud", "google cloud platform"]},
    {"skill_name": "Docker",                "skill_category": "Cloud & DevOps", "aliases": ["docker container"]},
    {"skill_name": "Kubernetes",            "skill_category": "Cloud & DevOps", "aliases": ["k8s"]},
    {"skill_name": "Jenkins",               "skill_category": "Cloud & DevOps", "aliases": ["jenkins"]},
    {"skill_name": "Terraform",             "skill_category": "Cloud & DevOps", "aliases": ["terraform"]},
    {"skill_name": "CI/CD",                 "skill_category": "Cloud & DevOps", "aliases": ["cicd", "continuous integration", "continuous deployment"]},
    {"skill_name": "Linux",                 "skill_category": "Cloud & DevOps", "aliases": ["unix", "linux os"]},
    {"skill_name": "GitHub Actions",        "skill_category": "Cloud & DevOps", "aliases": ["github actions"]},
    {"skill_name": "ArgoCD",                "skill_category": "Cloud & DevOps", "aliases": ["argocd", "argo cd"]},
    {"skill_name": "Prometheus",            "skill_category": "Cloud & DevOps", "aliases": ["prometheus monitoring"]},
    {"skill_name": "Grafana",               "skill_category": "Cloud & DevOps", "aliases": ["grafana"]},
    {"skill_name": "Helm",                  "skill_category": "Cloud & DevOps", "aliases": ["helm charts"]},
    {"skill_name": "OpenShift",             "skill_category": "Cloud & DevOps", "aliases": ["openshift", "red hat openshift"]},
    {"skill_name": "Serverless Architecture","skill_category": "Cloud & DevOps", "aliases": ["serverless", "faas"]},
    {"skill_name": "Edge Computing",        "skill_category": "Cloud & DevOps", "aliases": ["edge computing"]},
    {"skill_name": "Ansible",              "skill_category": "Cloud & DevOps", "aliases": ["ansible"]},
    {"skill_name": "Pulumi",               "skill_category": "Cloud & DevOps", "aliases": ["pulumi"]},
    {"skill_name": "Vault",                "skill_category": "Cloud & DevOps", "aliases": ["hashicorp vault"]},
    {"skill_name": "Istio",                "skill_category": "Cloud & DevOps", "aliases": ["istio service mesh"]},
    {"skill_name": "Datadog",              "skill_category": "Cloud & DevOps", "aliases": ["datadog monitoring"]},

    # ── Database ──────────────────────────────────────────────────────────────
    {"skill_name": "MySQL",         "skill_category": "Database", "aliases": ["mysql"]},
    {"skill_name": "PostgreSQL",    "skill_category": "Database", "aliases": ["postgres", "postgresql"]},
    {"skill_name": "MongoDB",       "skill_category": "Database", "aliases": ["mongo", "mongodb"]},
    {"skill_name": "Redis",         "skill_category": "Database", "aliases": ["redis cache"]},
    {"skill_name": "Cassandra",     "skill_category": "Database", "aliases": ["apache cassandra"]},
    {"skill_name": "Elasticsearch", "skill_category": "Database", "aliases": ["elastic search", "elk"]},
    {"skill_name": "SQLite",        "skill_category": "Database", "aliases": ["sqlite"]},
    {"skill_name": "Pinecone",      "skill_category": "Database", "aliases": ["pinecone"]},
    {"skill_name": "Weaviate",      "skill_category": "Database", "aliases": ["weaviate"]},
    {"skill_name": "ChromaDB",      "skill_category": "Database", "aliases": ["chroma", "chromadb"]},
    {"skill_name": "Snowflake",     "skill_category": "Database", "aliases": ["snowflake"]},
    {"skill_name": "BigQuery",      "skill_category": "Database", "aliases": ["google bigquery"]},
    {"skill_name": "Supabase",      "skill_category": "Database", "aliases": ["supabase"]},
    {"skill_name": "PlanetScale",   "skill_category": "Database", "aliases": ["planetscale"]},
    {"skill_name": "DynamoDB",      "skill_category": "Database", "aliases": ["aws dynamodb", "dynamodb"]},
    {"skill_name": "Neo4j",         "skill_category": "Database", "aliases": ["neo4j", "graph database"]},
    {"skill_name": "CockroachDB",   "skill_category": "Database", "aliases": ["cockroachdb"]},
    {"skill_name": "InfluxDB",      "skill_category": "Database", "aliases": ["influxdb"]},
    {"skill_name": "Oracle DB",     "skill_category": "Database", "aliases": ["oracle database", "oracle sql"]},
    {"skill_name": "MS SQL Server", "skill_category": "Database", "aliases": ["mssql", "sql server", "microsoft sql server"]},

    # ── Tools & Practices ─────────────────────────────────────────────────────
    {"skill_name": "Git",               "skill_category": "Tools & Practices", "aliases": ["github", "gitlab", "version control"]},
    {"skill_name": "Jira",              "skill_category": "Tools & Practices", "aliases": ["jira"]},
    {"skill_name": "Agile",             "skill_category": "Tools & Practices", "aliases": ["agile methodology"]},
    {"skill_name": "Scrum",             "skill_category": "Tools & Practices", "aliases": ["scrum methodology"]},
    {"skill_name": "REST API",          "skill_category": "Tools & Practices", "aliases": ["rest", "restful", "restful api"]},
    {"skill_name": "GraphQL",           "skill_category": "Tools & Practices", "aliases": ["graphql"]},
    {"skill_name": "Microservices",     "skill_category": "Tools & Practices", "aliases": ["microservice architecture"]},
    {"skill_name": "System Design",     "skill_category": "Tools & Practices", "aliases": ["system architecture"]},
    {"skill_name": "gRPC",              "skill_category": "Tools & Practices", "aliases": ["grpc"]},
    {"skill_name": "WebSockets",        "skill_category": "Tools & Practices", "aliases": ["websocket", "ws"]},
    {"skill_name": "OAuth",             "skill_category": "Tools & Practices", "aliases": ["oauth2", "oauth 2.0"]},
    {"skill_name": "OpenAPI",           "skill_category": "Tools & Practices", "aliases": ["swagger", "openapi spec"]},
    {"skill_name": "Postman",           "skill_category": "Tools & Practices", "aliases": ["postman"]},
    {"skill_name": "Figma",             "skill_category": "Tools & Practices", "aliases": ["figma"]},
    {"skill_name": "Notion",            "skill_category": "Tools & Practices", "aliases": ["notion"]},
    {"skill_name": "Confluence",        "skill_category": "Tools & Practices", "aliases": ["confluence"]},
    {"skill_name": "Kanban",            "skill_category": "Tools & Practices", "aliases": ["kanban board"]},
    {"skill_name": "TDD",               "skill_category": "Tools & Practices", "aliases": ["test driven development", "test-driven development"]},
    {"skill_name": "Code Review",       "skill_category": "Tools & Practices", "aliases": ["code review", "peer review"]},
    {"skill_name": "Design Patterns",   "skill_category": "Tools & Practices", "aliases": ["design patterns", "software patterns"]},
    {"skill_name": "Clean Code",        "skill_category": "Tools & Practices", "aliases": ["clean code", "solid principles"]},
    {"skill_name": "VS Code",           "skill_category": "Tools & Practices", "aliases": ["vscode", "visual studio code"]},
    {"skill_name": "IntelliJ IDEA",     "skill_category": "Tools & Practices", "aliases": ["intellij"]},

    # ── Cybersecurity ─────────────────────────────────────────────────────────
    {"skill_name": "Penetration Testing",       "skill_category": "Cybersecurity", "aliases": ["pentest", "pen testing", "pentesting"]},
    {"skill_name": "Ethical Hacking",           "skill_category": "Cybersecurity", "aliases": ["ethical hacker"]},
    {"skill_name": "SIEM",                      "skill_category": "Cybersecurity", "aliases": ["security information and event management"]},
    {"skill_name": "SOC",                       "skill_category": "Cybersecurity", "aliases": ["security operations center"]},
    {"skill_name": "Vulnerability Assessment",  "skill_category": "Cybersecurity", "aliases": ["vulnerability assessment"]},
    {"skill_name": "Network Security",          "skill_category": "Cybersecurity", "aliases": ["network security"]},
    {"skill_name": "Zero Trust Architecture",   "skill_category": "Cybersecurity", "aliases": ["zero trust", "ztna"]},
    {"skill_name": "OWASP",                     "skill_category": "Cybersecurity", "aliases": ["owasp top 10"]},
    {"skill_name": "Burp Suite",                "skill_category": "Cybersecurity", "aliases": ["burpsuite"]},
    {"skill_name": "Wireshark",                 "skill_category": "Cybersecurity", "aliases": ["wireshark"]},
    {"skill_name": "Cryptography",              "skill_category": "Cybersecurity", "aliases": ["cryptography", "encryption"]},
    {"skill_name": "IAM",                       "skill_category": "Cybersecurity", "aliases": ["identity and access management", "iam"]},
    {"skill_name": "Incident Response",         "skill_category": "Cybersecurity", "aliases": ["incident response"]},
    {"skill_name": "Threat Modeling",           "skill_category": "Cybersecurity", "aliases": ["threat modeling"]},
    {"skill_name": "Malware Analysis",          "skill_category": "Cybersecurity", "aliases": ["malware analysis"]},
    {"skill_name": "Nmap",                      "skill_category": "Cybersecurity", "aliases": ["nmap"]},
    {"skill_name": "Metasploit",                "skill_category": "Cybersecurity", "aliases": ["metasploit"]},

    # ── Domain Specific ───────────────────────────────────────────────────────
    {"skill_name": "Unity",             "skill_category": "Domain Specific", "aliases": ["unity3d", "unity engine"]},
    {"skill_name": "Unreal Engine",     "skill_category": "Domain Specific", "aliases": ["unreal", "ue4", "ue5"]},
    {"skill_name": "Blockchain",        "skill_category": "Domain Specific", "aliases": ["web3", "distributed ledger"]},
    {"skill_name": "SAP",               "skill_category": "Domain Specific", "aliases": ["sap erp"]},
    {"skill_name": "Salesforce CRM",    "skill_category": "Domain Specific", "aliases": ["salesforce", "sfdc"]},
    {"skill_name": "AR/VR Development", "skill_category": "Domain Specific", "aliases": ["ar vr", "augmented reality", "virtual reality", "xr development"]},
    {"skill_name": "WebGL",             "skill_category": "Domain Specific", "aliases": ["webgl"]},
    {"skill_name": "Shader Programming","skill_category": "Domain Specific", "aliases": ["shader", "glsl", "hlsl"]},
    {"skill_name": "Game Design",       "skill_category": "Domain Specific", "aliases": ["game design"]},
    {"skill_name": "Esports Analytics", "skill_category": "Domain Specific", "aliases": ["esports analytics"]},
    {"skill_name": "React Native",      "skill_category": "Domain Specific", "aliases": ["react-native"]},
    {"skill_name": "Flutter",           "skill_category": "Domain Specific", "aliases": ["flutter dart"]},
    {"skill_name": "Mobile Development","skill_category": "Domain Specific", "aliases": ["mobile dev", "android development", "ios development"]},
    {"skill_name": "Embedded Systems",  "skill_category": "Domain Specific", "aliases": ["embedded systems", "firmware"]},
    {"skill_name": "IoT",               "skill_category": "Domain Specific", "aliases": ["internet of things", "iot development"]},
    {"skill_name": "Robotics",          "skill_category": "Domain Specific", "aliases": ["robotics", "ros"]},
    {"skill_name": "Godot",             "skill_category": "Domain Specific", "aliases": ["godot engine"]},
    {"skill_name": "Phaser",            "skill_category": "Domain Specific", "aliases": ["phaser.js", "phaserjs"]},
    {"skill_name": "Android SDK",       "skill_category": "Domain Specific", "aliases": ["android sdk", "android studio"]},
    {"skill_name": "iOS SDK",           "skill_category": "Domain Specific", "aliases": ["ios sdk", "xcode"]},

    # ── Additional Programming ────────────────────────────────────────────────
    {"skill_name": "Objective-C",   "skill_category": "Programming", "aliases": ["objective c", "objc"]},
    {"skill_name": "Erlang",        "skill_category": "Programming", "aliases": ["erlang"]},
    {"skill_name": "Zig",           "skill_category": "Programming", "aliases": ["zig lang"]},
    {"skill_name": "Nim",           "skill_category": "Programming", "aliases": ["nim lang"]},
    {"skill_name": "Crystal",       "skill_category": "Programming", "aliases": ["crystal lang"]},

    # ── Additional Web ────────────────────────────────────────────────────────
    {"skill_name": "Storybook",     "skill_category": "Web", "aliases": ["storybook.js"]},
    {"skill_name": "Cypress",       "skill_category": "Web", "aliases": ["cypress testing"]},
    {"skill_name": "Playwright",    "skill_category": "Web", "aliases": ["playwright testing"]},
    {"skill_name": "Jest",          "skill_category": "Web", "aliases": ["jest testing"]},
    {"skill_name": "Vitest",        "skill_category": "Web", "aliases": ["vitest"]},

    # ── Additional Data & ML ──────────────────────────────────────────────────
    {"skill_name": "Flink",         "skill_category": "Data & ML", "aliases": ["apache flink"]},
    {"skill_name": "Databricks",    "skill_category": "Data & ML", "aliases": ["databricks"]},
    {"skill_name": "Great Expectations", "skill_category": "Data & ML", "aliases": ["great expectations", "data quality"]},
    {"skill_name": "Weights & Biases",   "skill_category": "Data & ML", "aliases": ["wandb", "weights and biases"]},
    {"skill_name": "DVC",           "skill_category": "Data & ML", "aliases": ["data version control", "dvc"]},

    # ── Additional Cloud & DevOps ─────────────────────────────────────────────
    {"skill_name": "Nginx",         "skill_category": "Cloud & DevOps", "aliases": ["nginx"]},
    {"skill_name": "Traefik",       "skill_category": "Cloud & DevOps", "aliases": ["traefik"]},
    {"skill_name": "Consul",        "skill_category": "Cloud & DevOps", "aliases": ["hashicorp consul"]},
    {"skill_name": "Packer",        "skill_category": "Cloud & DevOps", "aliases": ["hashicorp packer"]},
    {"skill_name": "Vagrant",       "skill_category": "Cloud & DevOps", "aliases": ["vagrant"]},

    # ── Additional Tools & Practices ──────────────────────────────────────────
    {"skill_name": "SonarQube",     "skill_category": "Tools & Practices", "aliases": ["sonarqube", "sonar"]},
    {"skill_name": "Nx",            "skill_category": "Tools & Practices", "aliases": ["nx monorepo"]},
    {"skill_name": "Turborepo",     "skill_category": "Tools & Practices", "aliases": ["turborepo"]},
    {"skill_name": "Linear",        "skill_category": "Tools & Practices", "aliases": ["linear app"]},
    {"skill_name": "Slack API",     "skill_category": "Tools & Practices", "aliases": ["slack api", "slack integration"]},

    # ── Soft Skills ───────────────────────────────────────────────────────────
    {"skill_name": "Communication",         "skill_category": "Soft Skills", "aliases": ["communication skills", "verbal communication"]},
    {"skill_name": "Problem Solving",       "skill_category": "Soft Skills", "aliases": ["problem-solving", "analytical problem solving"]},
    {"skill_name": "Teamwork",              "skill_category": "Soft Skills", "aliases": ["collaboration", "team player"]},
    {"skill_name": "Leadership",            "skill_category": "Soft Skills", "aliases": ["team leadership", "people management"]},
    {"skill_name": "Analytical Thinking",   "skill_category": "Soft Skills", "aliases": ["analytical thinking"]},
    {"skill_name": "Critical Thinking",     "skill_category": "Soft Skills", "aliases": ["critical thinking"]},
    {"skill_name": "Stakeholder Management","skill_category": "Soft Skills", "aliases": ["stakeholder management"]},
    {"skill_name": "Data Storytelling",     "skill_category": "Soft Skills", "aliases": ["data visualization storytelling"]},
    {"skill_name": "Time Management",       "skill_category": "Soft Skills", "aliases": ["time management"]},
    {"skill_name": "Adaptability",          "skill_category": "Soft Skills", "aliases": ["adaptability"]},
    {"skill_name": "Mentoring",             "skill_category": "Soft Skills", "aliases": ["mentoring", "coaching"]},
    {"skill_name": "Project Management",    "skill_category": "Soft Skills", "aliases": ["project management"]},
    {"skill_name": "Presentation Skills",   "skill_category": "Soft Skills", "aliases": ["presentation skills", "public speaking"]},
    {"skill_name": "Negotiation",           "skill_category": "Soft Skills", "aliases": ["negotiation skills"]},
    {"skill_name": "Conflict Resolution",   "skill_category": "Soft Skills", "aliases": ["conflict resolution"]},
    {"skill_name": "Emotional Intelligence","skill_category": "Soft Skills", "aliases": ["emotional intelligence", "eq"]},
    {"skill_name": "Decision Making",       "skill_category": "Soft Skills", "aliases": ["decision making"]},
    {"skill_name": "Cross-functional Collaboration", "skill_category": "Soft Skills", "aliases": ["cross functional", "cross-functional"]},
]


def get_taxonomy() -> list[dict]:
    """Return the full skill taxonomy as a list of dicts.

    Each dict has:
        skill_name (str): canonical skill name
        skill_category (str): one of the 10 defined categories
        aliases (list[str]): alternative names / abbreviations
    """
    return _TAXONOMY


def get_keyword_set() -> set[str]:
    """Return a flat set of all keywords (skill_names + aliases) lowercased for fast lookup."""
    keywords: set[str] = set()
    for entry in _TAXONOMY:
        keywords.add(entry["skill_name"].lower())
        for alias in entry["aliases"]:
            keywords.add(alias.lower())
    return keywords
